image: cr.agilicus.com/corp-tools/docker-compose

variables:
  DOCKER_DRIVER: overlay2
  PORT: 2375
  DOCKER_HOST: tcp://localhost:2375
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH
  HANGOUTS_SPACE: AAAAqAYKghI
  HANGOUTS_KEY: AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=kH8cc_W44ZzioakoUkFWkwSssem-9xH9K1r_0hWjuS4
  HANGOUTS_TOKEN: kH8cc_W44ZzioakoUkFWkwSssem-9xH9K1r_0hWjuS4
  HANGOUTS_THREAD: $CI_PROJECT_PATH
  HANGOUTS_MSG: $GITLAB_USER_LOGIN::$CI_JOB_STAGE $CI_PROJECT_PATH -- see $CI_PROJECT_URL/-/jobs/$CI_BUILD_ID\n$GIT_COMMIT_TITLE

services:
  - name: docker:dind

stages:
  - build
  - scan

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - "curl -X POST -H 'Content-Type: application/json'
    \"https://chat.googleapis.com/v1/spaces/$HANGOUTS_SPACE/messages?key=$HANGOUTS_KEY&token=$HANGOUTS_TOKEN&threadKey=$HANGOUTS_THREAD\"
    -d \"{\\\"text\\\":\\\"$HANGOUTS_MSG\\\"}\""

services:
- name: docker:dind

build:
  stage: build
  script:
  - echo Start build
  - docker pull $CONTAINER_IMAGE:latest || true
  - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_BUILD_REF --tag $CONTAINER_IMAGE:latest .
  - docker push $CONTAINER_IMAGE:$CI_BUILD_REF
  - docker push $CONTAINER_IMAGE:latest

scan:
  stage: scan
  artifacts:
    name: "$CI_PROJECT_PATH-$CI_COMMIT_REF_NAME"
    paths:
      - reports/
  script:
    - echo Analyse container for vulnerability
    - clairctl analyze --log-level debug $CONTAINER_IMAGE:$CI_BUILD_REF || true
    - echo Generate JSON report
    - clairctl report -f json $CONTAINER_IMAGE:$CI_BUILD_REF || true
    - echo Generate HTML report
    - clairctl report -f html $CONTAINER_IMAGE:$CI_BUILD_REF || true

