#!/bin/bash

log() {
    echo "$(date -Is): $*"
}

set -a

RESTIC_INTERVAL=${RESTIC_INTERVAL:-4}
RESTIC_BACKUP_DIR=${RESTIC_BACKUP_DIR:-/var/backups}
RESTIC_HOSTNAME=${RESTIC_HOSTNAME:-$(hostname)}
unset TERM

log "Startup $*"

if [ "$1" = "auto" ]
then
    # run rsyslog to help w/ cron debug
    rsyslogd

    # This will fail on subsequent runs, but that is ok
    /usr/bin/restic init >/dev/null 2>&1

    echo "Will automatically backup $RESTIC_BACKUP_DIR to $RESTIC_REPOSITORY every $RESTIC_INTERVAL hours"
    mkdir -p /var/spool/cron/crontabs  /etc/crontabs

    # minute hour day-of-month month day-of-week command
    echo 'MAILTO=""' > /tmp/crontab
    echo "$((RANDOM % 60)) */$RESTIC_INTERVAL * * * /backup.sh" >> /tmp/crontab
    crontab /tmp/crontab
    crontab -l
    rm -f /tmp/crontab

    log "cron: <<$(cat /etc/crontabs/root)>>"
    exec /usr/sbin/cron -f -L7
else
    exec /usr/bin/restic "$@"
fi

