#!/bin/sh

RESTIC_INTERVAL=${RESTIC_INTERVAL:-4}
RESTIC_BACKUP_DIR=${RESTIC_BACKUP_DIR:-/var/backups}
RESTIC_HOSTNAME=${RESTIC_HOSTNAME:-$(hostname)}
unset TERM

echo "args: <<$*>>"

if [ "$1" = "auto" ]
then
    # This will fail on subsequent runs, but that is ok
    /usr/bin/restic init >/dev/null 2>&1

    echo "Will automatically backup $RESTIC_BACKUP_DIR to $RESTIC_REPOSITORY every $RESTIC_INTERVAL hours"
    mkdir -p /var/spool/cron/crontabs /etc/crontabs

    # minute hour day-of-month month day-of-week command
    echo "$((RANDOM % 60)) */$RESTIC_INTERVAL * * * [ -n \"\$(ls $RESTIC_BACKUP_DIR)\" ] && /usr/bin/restic backup --cleanup-cache -q --host=$RESTIC_HOSTNAME $RESTIC_BACKUP_DIR" > /etc/crontabs/root
#    echo "*/1 * * * * /usr/bin/restic backup -q --hostname=$RESTIC_HOSTNAME $RESTIC_BACKUP_DIR" > /etc/crontabs/root
    ln -sf /etc/crontabs/root /var/spool/cron/crontabs/root
    exec /usr/sbin/cron -f
else
    exec /usr/bin/restic "$@"
fi
